apiVersion: apps/v1
kind: Deployment # Spins up and container and wraps it in a pod
metadata:
    name: client-depl
spec:
    replicas: 1 # number of same containers to spin up. A pod can have multiple containers.
    selector:
      matchLabels:
         app: client
    template:
       metadata:
         labels:
           app: client
       spec:
         containers: # List of containers to use. "-" signifies that is an array.
           - name: client
             image: johndoeups/client # Always get same image.":latest" tag is not working at this time.
             imagePullPolicy: Always # Always pull from docker hub.
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector: # Tell the service to direct incoming traffic to the pod with label of event-bus. See a deployment config named labels in template object above
    app: client
  type: ClusterIP # Cluster IP service. Governs/Establishes inter-pod communications
  ports:
    - name: client
      protocol: TCP
      port: 3000 # Entry port to the container. Keep it same as targetPort for easier understanding.
      targetPort: 3000 # This is a port being listened on in the container. In this case client react app port.
