apiVersion: apps/v1
kind: Deployment # Spins up and container and wraps it in a pod
metadata:
    name: event-bus-depl
spec:
    replicas: 1 # number of same containers to spin up. A pod can have multiple containers.
    selector:
      matchLabels:
         app: event-bus
    template:
       metadata:
         labels:
           app: event-bus
       spec:
         containers: # List of containers to use. "-" signifies that is an array.
           - name: event-bus
             image: johndoeups/event-bus:latest # Always get same image.":latest" tag is not working at this time.
             imagePullPolicy: Always # Always pull from docker hub.
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector: # Tell the service to direct incoming traffic to the pod with label of event-bus. See a deployment config named labels in template object above
    app: event-bus
  type: ClusterIP # Cluster IP service. Governs/Establishes inter-pod communications
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005 # Entry port to the container. Keep it same as targetPort for easier understanding.
      targetPort: 4005 # This is a port being listened on in the container. In this case event-bus node.js app port.
