apiVersion: apps/v1
kind: Deployment # Spins up and container and wraps it in a pod
metadata:
    name: query-depl
spec:
    replicas: 1 # number of same containers to spin up. A pod can have multiple containers.
    selector:
      matchLabels:
         app: query
    template:
       metadata:
         labels:
           app: query
       spec:
         containers: # List of containers to use. "-" signifies that is an array.
           - name: query
             image: johndoeups/query:latest # Always get same image.":latest" tag is not working at this time.
             imagePullPolicy: Always # Always pull from docker hub.
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector: # Tell the service to direct incoming traffic to the pod with label of event-bus. See a deployment config named labels in template object above
    app: query
  type: ClusterIP # Cluster IP service. Governs/Establishes inter-pod communications
  ports:
    - name: query
      protocol: TCP
      port: 4002 # Entry port to the container. Keep it same as targetPort for easier understanding.
      targetPort: 4002 # This is a port being listened on in the container. In this case query node.js app port.
